### ISSUE TITLE
🐛 _treeview windows build error  

### ISSUE THREAD

**Issue by ninetynin** [bdlukaa/fluent_ui#608] opened 2022-11-12 13:17 UTC
**Describe the bug**
This is the the output in debug console while building
```
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
Nuget is not installed.
Attempting to download nuget.
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/fluent_ui-4.0.3+1/lib/src/controls/navigation/tree_view.dart(833,21): error GE5CFE876: The method 'VoidCallbackIntent' isn't defined for the class '_TreeViewItem'. [F:\GITHUB REPOS\ninetynin\intspdfviewer\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/fluent_ui-4.0.3+1/lib/src/controls/navigation/tree_view.dart(840,21): error GE5CFE876: The method 'VoidCallbackIntent' isn't defined for the class '_TreeViewItem'. [F:\GITHUB REPOS\ninetynin\intspdfviewer\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/fluent_ui-4.0.3+1/lib/src/controls/navigation/tree_view.dart(852,21): error GE5CFE876: The method 'VoidCallbackIntent' isn't defined for the class '_TreeViewItem'. [F:\GITHUB REPOS\ninetynin\intspdfviewer\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'F:\GITHUB REPOS\ninetynin\intspdfviewer\build\windows\CMakeFiles\45ff2a17404926c87fa801d2fa00c8dc\flutter_windows.dll.rule;F:\GITHUB REPOS\ninetynin\intspdfviewer\build\windows\CMakeFiles\7b6ae8408c586eb6ee665c069a987412\flutter_assemble.rule;F:\GITHUB REPOS\ninetynin\intspdfviewer\windows\flutter\CMakeLists.txt' exited with code 1. [F:\GITHUB REPOS\ninetynin\intspdfviewer\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
Exited (sigterm)
```

**To Reproduce**
Nothing just building in windows and im getting the error I didnt do any change and nuget is because of webview_windows package justincase saying

**Screenshots**
![image](https://user-images.githubusercontent.com/91336664/201475769-4d72a811-23c3-43f2-8443-0d0c2eef4dce.png)

**Comment by bdlukaa** [comment] 2022-11-12 14:18
Duplicate of #561

**Closed** 2022-11-14 13:23 UTC
Labels: duplicate
