### ISSUE TITLE
PaneItemExpander🐛 

### ISSUE THREAD

**Issue by longfit** [bdlukaa/fluent_ui#819] opened 2023-04-30 00:03 UTC
Fluent_ui 4.5.0
use example 

I design menu item which paneItem under  PaneItemExpander as control group

I

When I set Nagivation Pane display mode at top
, click at last item ....

1>  set top mode display when click overflow display area
      which will be shown error as follow

throw FlutterError.fromParts(<DiagnosticsNode>[
                ErrorSummary('Duplicate GlobalKey$s detected in widget tree.'),
                // TODO(jacobr): refactor this code so the elements are clickable
                // in GUI debug tools.
![Screenshot from 2023-04-30 13-07-53](https://user-images.githubusercontent.com/4157794/235336935-51c994dc-7729-42a1-8ecd-4240ccb32247.png)

                ErrorDescription(
                  'The following GlobalKey$s $were specified multiple times in the widget tree. This will lead to '
                  'parts of the widget tree being truncated unexpectedly, because the second time a key is seen, '
                  'the previous instance is moved to the new location. The key$s $were:\n'
                  '- ${keyLabels.join("\n  ")}\n'
                  'This was determined by noticing that after$the widget$s with the above global key$s $were moved '
                  'out of $their$respective previous parent$s2, $those2 previous parent$s2 never updated during this frame, meaning '
                  'that $they either did not update at all or updated before the widget$s $were moved, in either case '
                  'implying that $they still $think that $they should have a child with $those global key$s.\n'
                  'The specific parent$s2 that did not update after having one or more children forcibly removed '
                  'due to GlobalKey reparenting $are:\n'
                  '- ${elementLabels.join("\n  ")}'
                  '\nA GlobalKey can only be specified on one widget at a time in the widget tree.',
                ),
              ]);

2) click last item expander can not work onTap event 

I don't know how to use the navigation View for menu paneitem and group the paneItem 

Could you  enhance the  example case where have PaneItemExpander menu Item ?

thanks
![Screenshot from 2023-04-30 13-07-53](https://user-images.githubusercontent.com/4157794/235336949-22a65ac8-2e50-4dd5-81fe-44a27295dfd5.png)

**Comment by bdlukaa** [comment] 2023-04-30 14:02
Duplicate of #812

**Closed** 2023-04-30 14:02 UTC
