### ISSUE TITLE
🐛 AutoSuggestBox Navigate by Arrow Keys Not Working

### ISSUE THREAD

**Issue by LambdaMan2K** [bdlukaa/fluent_ui#414] opened 2022-07-02 18:24 UTC
hey 

when I run the example app, I cannot use the arrow keys to navigate suggestion list. with up and down keys, they just move the line cursor  left and right in the textfield .  might just be a focus problem, but I would expect it to work like arrow keys to chose and then enter to select. 
I get the same behavior in the web demo.  

a side note, when I try to use arrow keys in the combobox  it works as expected.

I have  noticed similar issues reported but  they are closed for some reason.

running on windows 10 x64

**Comment by bdlukaa** [comment] 2022-07-03 12:06
Duplicate of #19

**Closed** 2022-07-03 12:07 UTC
Labels: duplicate
