### ISSUE TITLE
🐛 fluent_ui 4.1.5 build error

### ISSUE THREAD

**Issue by kwang87** [bdlukaa/fluent_ui#693] opened 2023-01-25 08:06 UTC
I had to flutter upgrade and fluent_ui 4.1.5 pub get today.
but it can't build now.

error code:
/C:/Users/kwang/AppData/Local/Pub/Cache/hosted/pub.dev/fluent_ui-4.1.5/lib/src/controls/inputs/slider.dart(359,8): error G76A9B1F6: The method '_CustomTrackShape.paint' has fewer named arguments than those of overridden method 'RoundedRectSliderTrackShape.paint'. [D:\0.Develop\prime_client\src\PRIME_Client\sgclientformacos\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/kwang/AppData/Local/Pub/Cache/hosted/pub.dev/fluent_ui-4.1.5/lib/src/controls/inputs/slider.dart(359,8): error G76A9B1F6: The method '_CustomTrackShape.paint' doesn't have the named parameter 'secondaryOffset' of overridden method 'RoundedRectSliderTrackShape.paint'. [D:\0.Develop\prime_client\src\PRIME_Client\sgclientformacos\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: 'D:\0.Develop\prime_client\src\PRIME_Client\sgclientformacos\build\windows\CMakeFiles\fb798fe18a1e583de38ed8257fe66401\flutter_windows.dll.rule;D:\0.Develop\prime_client\src\PRIME_Client\sgclientformacos\build\windows\CMakeFiles\aa9fa5d0792c4d83da5226853edec2d1\flutter_assemble.rule'�� ���� ����� ���� ���尡 ����Ǿ����ϴ�(�ڵ� 1). [D:\0.Develop\prime_client\src\PRIME_Client\sgclientformacos\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.

I try to downgrade fluent_ui version to 4.1.0 but same error code repeat(fluent_ui-4.1.5).
: 
flutter clean
pubspec.yaml -> edit code: fluent_ui: ^4.1.0  
flutter pub get 
flutter build windows

**Comment by damywise** [comment] 2023-01-25 08:11
I believe this is a duplicate of #568. You probably upgraded flutter 3.7.0 or the master channel which has breaking changes.

**Comment by damywise** [comment] 2023-01-25 08:14
The fix is either to:
1. Downgrade Flutter
2. Use [this](https://github.com/Gorter-dev/fluent_ui/tree/hotfix/flutter_master) version
3. Wait for a fix

**Comment by Dbone29** [comment] 2023-01-25 12:58
The fix is to add one line to the paint function in this file:

fluent_ui/lib/src/controls/inputs/slider.dart

This is the line to fix it:

Offset? secondaryOffset,

and this is how it would look like like:

@override
  void paint(
    PaintingContext context,
    Offset offset, {
    required RenderBox parentBox,
    required m.SliderThemeData sliderTheme,
    required Animation<double> enableAnimation,
    required TextDirection textDirection,
    required Offset thumbCenter,
    Offset? secondaryOffset,
    bool isDiscrete = false,
    bool isEnabled = false,
    double additionalActiveTrackHeight = 0,
  }) {


This fix works for me.

Everything else are actually only warnings.

If you want I can open a pull request. With all my fixes for Flutter 3.7.

**Closed** 2023-01-25 14:45 UTC
