### ISSUE TITLE
🐛 Flutter Error when running example on macos + VS Code

### ISSUE THREAD

**Issue by tofutim** [bdlukaa/fluent_ui#94] opened 2021-11-12 08:00 UTC
FlutterError (This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.)

1. Run on mac from VS code
2. Attempt to resize window or change the setting to light
3. Error

![image](https://user-images.githubusercontent.com/157766/141431403-c66b719d-0548-4c18-aa1e-3ea741664426.png)

Could be just my machine but I don't think so.

**Comment by henry2man** [comment] 2021-11-12 09:18
@tofutim It looks a duplicate of https://github.com/bdlukaa/fluent_ui/issues/71, could be?

**Closed** 2021-11-12 13:50 UTC
Labels: duplicate
