### ISSUE TITLE
🐛 PaneItemExpander unwant result

### ISSUE THREAD

**Issue by longfit** [bdlukaa/fluent_ui#870] opened 2023-06-28 14:19 UTC
Fluent_ui 4.6.2

I have copied your PaneItemExpander your sample code and class  _NavigationBodyItem 

 into main.dart

paste PaneItemExpander(.....) into originalItems =[
 PaneItem(
      key: const Key('/'),
      icon: const Icon(FluentIcons.home),
      title: const Text('Home'),
      body: const SizedBox.shrink(),
      onTap: () {
        if (router.location != '/') router.pushNamed('home');
      },
    ),
    PaneItemExpander(
      icon: const Icon(FluentIcons.group_list),
      title: const Text('Group 1'),
      body: const _NavigationBodyItem(
        header: 'Group 1 Expander',
        content: Text('Group 1 content display'),
      ),
      items: [
        PaneItemHeader(header: const Text('Item Group 1')),
        PaneItem(
          icon: const Icon(FluentIcons.mail),
          title: const Text('mail'),
          body: const _NavigationBodyItem(),
        ),
        PaneItem(
          icon: const Icon(FluentIcons.calendar),
          title: const Text('Calendar'),
          body: const _NavigationBodyItem(),
        ),
      ],
    ),
.....
.....

It Can show PanItemExpander but client Group and item without any context result

at right hand side view.

Q1 Is misUnderstand to use the PaneItemExpander ?

![image](https://github.com/bdlukaa/fluent_ui/assets/4157794/08c2fff0-93e3-4621-91ad-412e5ab95745)

**Comment by bdlukaa** [comment] 2023-07-02 23:45
You need to either use a nested navigator or use the index-based navigation. As I can infer from the provided snippet, the router is pushed when clicked any button on the left, but it is not triggered when the pane item expander is pressed

**Comment by longfit** [comment] 2023-07-03 06:02
Thanks, 
Where Can I find the snippet shown nested navigator or index-based navigation.
1. I don't know to change (Group Pane Item)  my pane item expander From left is pressed ??

**Comment by bdlukaa** [comment] 2023-07-05 01:59
Seems like the issue is the same as #859

**Comment by longfit** [comment] 2023-07-05 13:00
the shown case is using fluent_ui 4.62
By My understanding,  will be fixed later version ??

**Comment by bdlukaa** [comment] 2023-07-05 16:44
Yes. Don't forget to call `if (router.location != '/') router.pushNamed('home');` (with the necessary changes), on the subitems of pane item expander as well. Closing as a duplicate of #859

**Closed by bdlukaa** 2023-07-05 16:44 UTC
