### ISSUE TITLE
🐛 Compatibility issues with flutter 3.13.0

### ISSUE THREAD

**Issue by kjxbyz** [bdlukaa/fluent_ui#916] opened 2023-08-17 01:57 UTC
**Describe the bug**
```
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/fluent_ui-4.7.2/lib/src/controls/form/selection_controls.dart:121:30: Error: The parameter 'clipboardStatus' of the method '_FluentTextSelectionControls.buildToolbar' has type 'ClipboardStatusNotifier?', which does not match the corresponding type, 'ValueListenable<ClipboardStatus>?', in the overridden method, 'TextSelectionControls.buildToolbar'.
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by longfit** [comment] 2023-08-17 06:28
so am I when upgrade 3.10.6 to 3.13.0

hence , I downgrade to 3.10.6 is working properly

**Comment by h3x4d3c1m4l** [comment] 2023-08-17 09:37
Hi! Already working on it: https://github.com/bdlukaa/fluent_ui/pull/915

For now you can switch to the git version (make sure to set `ref` to the branch name), but make sure to switch to the release version once it is released.

**Comment by bdlukaa** [comment] 2023-08-17 11:26
Duplicate of #865

**Closed by bdlukaa** 2023-08-17 11:26 UTC
