### ISSUE TITLE
🐛 PaneItemExpander error "A FlyoutController was used after being disposed".

### ISSUE THREAD

**Issue by adpmhel24** [bdlukaa/fluent_ui#857] opened 2023-06-10 14:22 UTC
when clicking the items of PaneItemExpander i got an error of A FlyoutController was used after being disposed.

**Comment by adpmhel24** [comment] 2023-06-10 14:54
https://github.com/bdlukaa/fluent_ui/assets/40779451/e35c7f62-6bae-44fc-915b-a70612f09830

**Comment by bdlukaa** [comment] 2023-06-11 13:54
What version of `fluent_ui` are you using? Probably a duplicate of #818

_please fill the issue template next time_

**Comment by adpmhel24** [comment] 2023-06-12 11:40
> What version of `fluent_ui` are you using? Probably a duplicate of #818
> 
> _please fill the issue template next time_

Even though the displayMode is compact

**Comment by bdlukaa** [comment] 2023-07-05 16:42
Sorry, but I was not able to reproduce this issue. Can you try it on the example application?

**Comment by Quintonvv** [comment] 2023-07-10 12:26
I created a web application for flutter, I get the same errors.

When I use the app in Fullscreen with the expanded menu, the error does not appear, however when its compact or even closed (mobile) I get an error related to FlyOut.

Error on conpact:  A FlyoutController was used after being disposed.
Error when on mobile: "This controller must be attached to a FlyoutTarget".

**Closed** 2023-08-27 23:31 UTC
Labels: bug
