### ISSUE TITLE
🐛 AutoSuggestBoxItem onSelected

### ISSUE THREAD

**Issue by adpmhel24** [bdlukaa/fluent_ui#705] opened 2023-01-28 17:15 UTC
Is there a bug in onSelected property? Ive tried printing the value in onSelected function but doesnt have any result, same as onChanged, only userInput and cleared was triggered.

**Comment by h3x4d3c1m4l** [comment] 2023-01-29 02:07
This might be a duplicate of #698... does it work when you press <enter> on your keyboard?

**Closed** 2023-01-30 06:19 UTC
