### ISSUE TITLE
There is no information in the documentation about some widgets.

### ISSUE THREAD

**Issue by dimstr** [bdlukaa/fluent_ui#159] opened 2022-02-06 18:25 UTC
In the example on the path [fluent_ui/example/lib/screens/inputs.dart on the 110th](https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/screens/inputs.dart#L110) line there is a mica widget, but there is no information about it in your documentation.

**Comment by bdlukaa** [comment] 2022-02-07 19:08
A lot of widgets aren't documentated or a poorly documentated :/

Duplicate of https://github.com/bdlukaa/fluent_ui/issues/40

**Closed by bdlukaa** 2022-02-07 19:08 UTC
