### ISSUE TITLE
PaneItemExpander not in new version of fluent ui

### ISSUE THREAD

**Issue by omar0141** [bdlukaa/fluent_ui#258] opened 2022-03-30 17:46 UTC
I can't use PaneItemExpander in new version of fluent ui

**Comment by bdlukaa** [comment] 2022-03-30 22:37
There has never been a PaneItemExpander

**Comment by bdlukaa** [comment] 2022-03-31 18:52
There's currently no way.

Closing as a duplicate of #205

**Closed** 2022-03-31 18:52 UTC
