### ISSUE TITLE
🐛 Little jank when the mouse leaves or enters the screen

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#778] opened 2023-03-17 15:22 UTC
**Describe the bug**

Maybe related to #777 

When I tested, I see on the performance tab a jank when the mouse leaves or enters the screen. Maybe it's a normal behaviour from Flutter, I don't tested on a sample material app.

But maybe we have too much rebuild on mouse enter/leave event.

![focus_jank](https://user-images.githubusercontent.com/8223773/225947445-983effa2-707e-47af-ad29-373b32247d4f.gif)

**Comment by bdlukaa** [comment] 2023-07-05 17:02
Sorry, but I could not reproduce this behavior using the latest specs. Maybe it's been fixed from the flutter team.

Closing as not planned

**Closed by bdlukaa** 2023-07-05 17:02 UTC
Labels: question
