### ISSUE TITLE
🐛 PaneItem indicator inconsistent with native UI

### ISSUE THREAD

**Issue by FantixX** [bdlukaa/fluent_ui#1136] opened 2024-11-16 13:38 UTC
**Describe the bug**
As seen in the GIFs, the indicator does not match the native one from the Windows Settings App

**To Reproduce**
Always occurs

**Expected behavior**

https://github.com/user-attachments/assets/fb4fed08-4db5-4395-9766-55dece76cba6

**Screenshots**

https://github.com/user-attachments/assets/eea4c591-2a3a-485b-a89f-99ed26a18ab6

**Additional context**
---

**Comment by bdlukaa** [comment] 2024-11-16 17:04
Duplicate of #540. Please read #919.

**Closed by bdlukaa** 2024-11-16 17:04 UTC
