### ISSUE TITLE
🐛 A double click in the text on a zone without text does not select the text.

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#794] opened 2023-03-28 19:45 UTC
**Describe the bug**

If we double click on the text in a textbox, the text is selected. But if we click on an "empty" area of the textbox, the text if not selected.

For example, if we double click here:

![image](https://user-images.githubusercontent.com/8223773/228349767-0d1f7f44-41ce-4274-bef2-e167b8967fa8.png)

On Windows that's generally the case (and that's the case on WinUI3 Gallery).

**Comment by bdlukaa** [comment] 2023-03-28 21:13
This looks more like a Flutter issue. We make use of Flutter's `EditableText`.

I don't think we can workaround this issue in any ways because we'd intercept taps, and that can cause unexpected issue

**Comment by bdlukaa** [comment] 2023-07-05 17:00
This is not reproducible with the latest version of `fluent_ui` and Flutter. Closing as not planned

**Closed by bdlukaa** 2023-07-05 17:00 UTC
Labels: bug
