### ISSUE TITLE
how keep pageview state?

### ISSUE THREAD

**Issue by jonahzheng** [bdlukaa/fluent_ui#169] opened 2022-02-09 14:25 UTC
NavigationPane change page, how keep pageview state?  like web browser
ex:
enter something into Formspage, and change to colorspage, 
and return to Formspage, the contents of the input in Formspage are not lost.

**Comment by bdlukaa** [comment] 2022-02-09 17:34
Duplicate of #95

**Closed by bdlukaa** 2022-02-09 17:34 UTC
