### ISSUE TITLE
Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by fisforfaheem** [bdlukaa/fluent_ui#186] opened 2022-02-17 12:51 UTC
![image](https://user-images.githubusercontent.com/35878088/154485379-c19217c7-2bb8-410c-a156-f42a3cb8e968.png)

**Comment by WinXaito** [comment] 2022-02-17 14:21
It's not only a problem with Fluent:

- https://stackoverflow.com/questions/71128613/how-to-avoid-any-binding-null-error-and-get-code-better
- https://github.com/juliuscanute/qr_code_scanner/issues/487
- https://github.com/felangel/flow_builder/issues/81

The error seems to be on `master` channel of Flutter. We only support stanle release.

If necessary, we will fix that on the next flutter release.

Btw, it's only a warning.

**Comment by fisforfaheem** [comment] 2022-02-17 17:13
Yeah, but i think it is easier to change, could you please have a look, as
I am using flutter master because it support flutter web much better than
stable version please have a look

**Comment by WinXaito** [comment] 2022-02-17 18:53
Yeah but the problem is that if we fix the problem for the master branch, we will break the current stable release. So we can’t do that.

**Comment by fisforfaheem** [comment] 2022-02-17 20:11
Thanks :) , One suggestion though you make a beta version of the package as
well for the people who want to stay on beta version...like if you goto GET
package at pub.dev... you can see they have two stuff going on...just a
suggestion though


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/18/22,
01:09:19 AM

**Comment by WinXaito** [comment] 2022-02-18 09:02
@bdlukaa do you think it's possible ? 

Maybe see to create a `beta` or `futur` branch that support master channel of Flutter. Who's is pushed automatically to pub.dev with a CI.

**Comment by bdlukaa** [comment] 2022-02-20 11:42
@WinXaito it'd be tough to maintain this

**Comment by WinXaito** [comment] 2022-02-20 18:36
I agree.

And as we have always said, we now have the stable version of Flutter.
Moreover, the Flutter and fluent releases are relatively fast.

@fisforfaheem If you really want that, you can temporary fork and fix the project.

I close this issue, please reopen if you do not agree or if you have other elements to add.

**Comment by WinXaito** [comment] 2022-02-21 09:57
Reopening to keep track when the new Flutter release comes out.

**Comment by fisforfaheem** [comment] 2022-02-21 10:11
Thanks a lot.

**Comment by fisforfaheem** [comment] 2022-02-21 10:11
Would try forking, Also I am impressed by the amount of work you do and
your dedication.

**Comment by MalcolmMielle** [comment] 2022-05-13 13:41
This is now in stable sadly :/

**Comment by bdlukaa** [comment] 2022-05-13 17:44
Fixed by #325

**Closed by bdlukaa** 2022-05-13 17:44 UTC
Labels: blocked
