### ISSUE TITLE
🐛 error in beta flutter version

### ISSUE THREAD

**Issue by lyming99** [bdlukaa/fluent_ui#646] opened 2022-12-09 20:37 UTC
error log
```
pub.flutter-io.cn/fluent_ui-4.1.1/lib/src/controls/inputs/slider.dart(363,8):
 error GE5CFE876: The method '_CustomTrackShape.paint' has fewer named arguments than those of overridden method 'RoundedRectSliderTrackShape.paint'.
```

**Comment by bdlukaa** [comment] 2022-12-10 13:41
Duplicate of #658

**Closed by bdlukaa** 2022-12-10 13:41 UTC
