### ISSUE TITLE
`NavigationView` seems to re-render all tabs every time you switch tabs

### ISSUE THREAD

**Issue by FengZi-lv** [bdlukaa/fluent_ui#922] opened 2023-08-25 03:40 UTC
**Describe the bug**

While I was constructing my application using both `Builder` and `NavigationView`, I stumbled upon an oddity: it appears that `NavigationView` re-renders all tabs every time a tab switch occurs. Rendering unnecessary pages every time will result in a wasteful consumption of resources.

**To Reproduce**
1. Clone [sample program](https://github.com/bdlukaa/fluent_ui/tree/master/example) to local
2. Open `lib\screens\inputs\button.dart` or any other page and replace `Builder` with the parent component of this page, for example:

```dart
// lib\screens\inputs\button.dart

@override
Widget build(BuildContext context) {

  // ignore some code unrelated to the problem

  return Builder(  // add this line
    // add this line
    // every time you switch tabs, this code will be called
    print('re-rendered button page');
    return ScaffoldPage.scrollable(
      header: const PageHeader(title: Text('Button')),
      children: [
        // ignore some widget unrelated to the problem
      ]);
  );
}
```
3. Switch tabs at will, and you will see many outputs of `re-rendered button page` from the console

**Expected behavior**
Only when you switch to the Button tab, will the Button page be rendered.

**Screenshots**

https://github.com/bdlukaa/fluent_ui/assets/59948673/ff8e8820-86c9-4310-bbc9-31b18f82ec8c

**Comment by FengZi-lv** [comment] 2023-08-25 05:50
**Supplementary explanation**
I found that this seems to be related to the use of `go_router`, when I do not use `go_router`, it does not trigger this issue.

**Comment by bdlukaa** [comment] 2023-08-25 12:29
Duplicate of #856?

**Comment by FengZi-lv** [comment] 2023-08-26 03:55
> Duplicate of #856?

My purpose is not to keep state, but not to render other unnecessary pages at the same time.
I tried `StatefulShellRoute` according to #856, but it didn't solve my problem.

I found a workaround: use `GoRouter.goNamed` instead of `GoRouter.pushNamed`, which magically solved my problem.
```dart
  List<NavigationPaneItem> headerItems = [
    PaneItem(
      key: const Key('/'),
      icon: const Icon(
        FluentIcons.chat_24_regular,
        size: 18,
      ),
      title: Text(pageTitle['/'] ?? ''),
      body: const SizedBox.shrink(),
      onTap: () {
        if (routerLocation != '/') {
          router.goNamed('chat');
          // router.pushNamed('chat');
        }
      },
    ),
  ...
];
```

**Comment by bdlukaa** [comment] 2023-08-27 22:56
Seems like it's not an issue with the library then.

The example app already uses `.go` to navigate through items.

**Closed by bdlukaa** 2023-08-27 22:56 UTC
