### ISSUE TITLE
Fluent UI is not letting me build Windows Application🐛 

### ISSUE THREAD

**Issue by rohsaurus** [bdlukaa/fluent_ui#263] opened 2022-04-01 21:40 UTC
**Describe the bug**
MSBuild reports null warnings regarding widget bindings and then exits with the error MSB8066; Only happens when using FluentUI. If running with MaterialApp instead, runs just fine.

**To Reproduce**
1. Create a new flutter project and import fluent_ui dart
2. Create a simple program using fluent_ui such as : 
`class MyApp extends StatelessWidget {
@override
Widget build(BuildContext context) {
return FluentApp();
}
}`
4. Run the program for Windows and get the following error messages after a few null warnings regarding Fluent_UI: error MSB8066: Custom build for 'C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\CMakeFiles\5435b8608448b3e0be9e292ad0ac4416\flutter_windows.dll.rule;C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\CMakeFiles\a7fc65a647e1e08abf695d486b105279\flutter_assemble.rule' exited with code 1. 
5. Note that running the same application, but instead using MaterialApp works and compiles perfectly. 

**Expected behavior**
The application to compile properly and run.

**Screenshots**

**Additional context**
I have looked and attempted several fixes on this github repo and the official Flutter repository as well, with no success. I have also reinstalled VS 2022.

Full Error Message Log:
`../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/form/selection_controls.dart(26,29): error G4906CC7E: The parameter 'clipboardStatus' of the method '_FluentTextSelectionControls.buildToolbar' has type 'ClipboardStatusNotifier', which does not match the corresponding type, 'ClipboardStatusNotifier?', in the overridden method, 'TextSelectionControls.buildToolbar'. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/inputs/dropdown_button.dart(350,20): warning G1E0FE241: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/navigation/navigation_view/indicators.dart(120,20): warning G1E0FE241: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/navigation/navigation_view/indicators.dart(126,20): warning G1E0FE241: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/surfaces/tooltip.dart(190,41): warning G1E0FE241: Operand of null-aware operation '!' has type 'RendererBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/surfaces/tooltip.dart(197,21): warning G1E0FE241: Operand of null-aware operation '!' has type 'RendererBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/surfaces/tooltip.dart(201,20): warning G1E0FE241: Operand of null-aware operation '!' has type 'GestureBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/surfaces/tooltip.dart(250,25): warning G1E0FE241: Operand of null-aware operation '!' has type 'RendererBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/surfaces/tooltip.dart(463,20): warning G1E0FE241: Operand of null-aware operation '!' has type 'GestureBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/surfaces/tooltip.dart(465,21): warning G1E0FE241: Operand of null-aware operation '!' has type 'RendererBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/form/combo_box.dart(1075,54): warning G1E0FE241: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/form/combo_box.dart(1082,20): warning G1E0FE241: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/controls/form/combo_box.dart(1084,20): warning G1E0FE241: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.9.1/lib/src/styles/acrylic.dart(93,20): warning G1E0FE241: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
G:\Visual_Studio_2022\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(245,5): error MSB8066: Custom build for 'C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\CMakeFiles\5435b8608448b3e0be9e292ad0ac4416\flutter_windows.dll.rule;C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\CMakeFiles\a7fc65a647e1e08abf695d486b105279\flutter_assemble.rule' exited with code 1. [C:\Users\Rohan\Documents\coding_projects\fluent_ui_test\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.`

Flutter doctor -v:
`PS C:\Users\Rohan\Documents\coding_projects\fluent_ui_test> flutter doctor -v
[√] Flutter (Channel master, 2.13.0-0.0.pre.84, on Microsoft Windows [Version 10.0.19043.1586], locale en-US)
    • Flutter version 2.13.0-0.0.pre.84 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a3514c77c6 (3 weeks ago), 2022-03-14 15:00:19 -0700
    • Engine revision 6001d2ed58
    • Dart version 2.17.0 (build 2.17.0-192.0.dev)
    • DevTools version 2.11.4

[X] Android toolchain - develop for Android devices
    • Android SDK at C:\
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
    • Visual Studio at G:\Visual_Studio_2022
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.1)
    • Android Studio at E:\Development Frameworks\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\Rohan\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5457.46
    • Flutter plugin version 65.2.3
    • Dart plugin version 212.5742

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1586]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.55

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
PS C:\Users\Rohan\Documents\coding_projects\fluent_ui_test>
`

**Comment by bdlukaa** [comment] 2022-04-01 21:45
Duplicate of #186. Please use the flutter stable channel

**Closed by bdlukaa** 2022-04-01 21:45 UTC
