### ISSUE TITLE
Mac Os Not Work when I Try to Enlarge window it go in Crash🐛 

### ISSUE THREAD

**Issue by nio74** [bdlukaa/fluent_ui#280] opened 2022-04-10 08:47 UTC
I was trying your Example App on my mac but not work when I enlarge the window, 

![image](https://user-images.githubusercontent.com/15077816/162610202-f66ba9d6-24cf-44b2-9a17-461bad0f33f4.png)

**Comment by bdlukaa** [comment] 2022-04-10 10:45
See #279

Duplicate of #71

**Closed** 2022-04-10 10:46 UTC
Labels: blocked
