### ISSUE TITLE
Some error reported when i run example🐛 

### ISSUE THREAD

**Issue by dev-lake** [bdlukaa/fluent_ui#665] opened 2022-12-30 01:00 UTC
![image](https://user-images.githubusercontent.com/28824748/210024685-28e82810-b44c-4b4d-8db2-5c6c69dc308a.png)

**Comment by bdlukaa** [comment] 2022-12-31 17:48
Duplicate of https://github.com/bdlukaa/system_theme/issues/8

**Closed by bdlukaa** 2022-12-31 17:48 UTC
