### ISSUE TITLE
Chevron Arrow in Scrollbar

### ISSUE THREAD

**Issue by iAkashPattnaik** [bdlukaa/fluent_ui#1115] opened 2024-09-09 16:47 UTC
**Is your feature request related to a problem? Please describe.**
To look more native like fluent_ui the arrow button are needed on the end's of a vertical `Scrollbar`.

**Describe the solution you'd like**
Would love to see this kind of functionality being added to `Scrollbar`?

**Additional context**

https://github.com/user-attachments/assets/5e3e1f7f-f12e-4612-98d7-730a9846bc54

**Comment by bdlukaa** [comment] 2024-09-09 16:54
Duplicate of #14, which is blocked.

**Closed by bdlukaa** 2024-09-09 16:54 UTC
