### ISSUE TITLE
4.7.2 is broken with new flutter 3.13.0 release on 8/16/23🐛 

### ISSUE THREAD

**Issue by ghigh** [bdlukaa/fluent_ui#918] opened 2023-08-17 15:52 UTC
Flutter version 3.13.0 on channel stable
Framework revision efbf63d9c6
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

 Error: The parameter 'clipboardStatus' of the method '_FluentTextSelectionControls.buildToolbar' has type 'ClipboardStatusNotifier?', which does not match the corresponding type, 'ValueListenable<ClipboardStatus>?', in the overridden method, 'TextSelectionControls.buildToolbar'.
selection_controls.dart:121
- 'ClipboardStatusNotifier' is from 'package:flutter/src/widgets/text_selection.dart' ('../../flutter/packages/flutter/lib/src/widgets/text_selection.dart').
text_selection.dart:1

- 'ValueListenable' is from 'package:flutter/src/foundation/change_notifier.dart' ('../../flutter/packages/flutter/lib/src/foundation/change_notifier.dart').
change_notifier.dart:1
- 'ClipboardStatus' is from 'package:flutter/src/widgets/text_selection.dart' ('../../flutter/packages/flutter/lib/src/widgets/text_selection.dart').
text_selection.dart:1

**Comment by bdlukaa** [comment] 2023-08-17 16:57
Duplicate of #865

**Closed by bdlukaa** 2023-08-17 16:57 UTC
