### ISSUE TITLE
build issue when using "TextBox" widget in the file "text_box.dart"🐛 

### ISSUE THREAD

**Issue by Yassinealsmayli** [bdlukaa/fluent_ui#731] opened 2023-02-09 19:50 UTC
**Describe the bug**
it take me a while searching in the internet for fix to this bug but never find a solution but after using the command "flutter run -d windows -v" i find the file causing the problem it was "text_box.dart" in the "fluent_ui" folder im using the 4.2 version 

**To Reproduce**

 to fix the issue:

1. go to : ".\fluent_ui-4.2.0\lib\src\controls\form\text_box.dart"
2. at line 28 change details type from "TapUpDetails" to  "TapDragUpDetails"
3. at line 36 change details type from "DragEndDetails" to "TapDragEndDetails"
4. and thats it this how i fix it .

**Expected behavior**
this is the error:
`../../../AppData/Local/Pub/Cache/hosted/pub.dev/fluent_ui-4.2.0/lib/src/controls/form/text_box.dart(28,3
5): error G4906CC7E: The parameter 'details' of the method
'_TextBoxSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match   
the corresponding type, 'TapDragUpDetails', in the overridden method,
'TextSelectionGestureDetectorBuilder.onSingleTapUp'. [C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dev/fluent_ui-4.2.0/lib/src/controls/form/text_box.dart(36,4
2): error G4906CC7E: The parameter 'details' of the method
'_TextBoxSelectionGestureDetectorBuilder.onDragSelectionEnd' has type 'DragEndDetails', which does not  
match the corresponding type, 'TapDragEndDetails', in the overridden method,
'TextSelectionGestureDetectorBuilder.onDragSelectionEnd'. [C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dev/fluent_ui-4.2.0/lib/src/controls/form/text_box.dart(30,2
5): error GC2F972A8: The argument type 'TapUpDetails' can't be assigned to the parameter type
'TapDragUpDetails'. [C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\flutter\flutter_assemble.vcxproj]
E:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066:
Custom build for 'C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\CMakeFiles\3da7f94c52d99192304875bf460b166e\flutter_windows.
dll.rule;C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\CMakeFiles\a94922094c37b70d59e42388dae2871c\flutter_assemble
.rule' exited with code 1. [C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dev/fluent_ui-4.2.0/lib/src/controls/form/text_box.dart(28,3
5): error G4906CC7E: The parameter 'details' of the method
'_TextBoxSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match   
the corresponding type, 'TapDragUpDetails', in the overridden method,
'TextSelectionGestureDetectorBuilder.onSingleTapUp'. [C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\flutter\flutter_assemble.vcxproj]
[   +2 ms]   [        ]
../../../AppData/Local/Pub/Cache/hosted/pub.dev/fluent_ui-4.2.0/lib/src/controls/form/text_box.dart(36,4
2): error G4906CC7E: The parameter 'details' of the method
'_TextBoxSelectionGestureDetectorBuilder.onDragSelectionEnd' has type 'DragEndDetails', which does not  
match the corresponding type, 'TapDragEndDetails', in the overridden method,
'TextSelectionGestureDetectorBuilder.onDragSelectionEnd'. [C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\flutter\flutter_assemble.vcxproj]
[   +2 ms]   [        ]
../../../AppData/Local/Pub/Cache/hosted/pub.dev/fluent_ui-4.2.0/lib/src/controls/form/text_box.dart(30,2
5): error GC2F972A8: The argument type 'TapUpDetails' can't be assigned to the parameter type
'TapDragUpDetails'. [C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\flutter\flutter_assemble.vcxproj]
[   +4 ms]   E:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error       
MSB8066: Custom build for 'C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\CMakeFiles\3da7f94c52d99192304875bf460b166e\flutter_windows.
dll.rule;C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\CMakeFiles\a94922094c37b70d59e42388dae2871c\flutter_assemble
.rule' exited with code 1. [C:\Users\wolfb\Desktop\os
project\os_algorithms_project\build\windows\flutter\flutter_assemble.vcxproj]
 #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:738:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1279:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9) 
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
`

**Comment by bdlukaa** [comment] 2023-02-10 01:34
Duplicate of #710

**Closed** 2023-02-10 01:34 UTC
Labels: duplicate
