### ISSUE TITLE
🐛 Incomplete animation between navigator pane transition

### ISSUE THREAD

**Issue by TENX-S** [bdlukaa/fluent_ui#1003] opened 2023-12-29 05:31 UTC
The fluent_ui example:

![1](https://github.com/bdlukaa/fluent_ui/assets/40336192/fc616af6-c7ba-4656-92ae-3e997d75a39d)

The WinUI 3 Gallery example:

![2](https://github.com/bdlukaa/fluent_ui/assets/40336192/714d5435-79b1-4671-b305-f7c46e07eeae)

If we select a pane in ascending order (in a top-down way), the animation breaks up as follows:

1. The blue indicator stretch to the bottom of the previous pane.
![image](https://github.com/bdlukaa/fluent_ui/assets/40336192/c805f47d-d91d-42b1-bc79-9f76acc47c8a)

2. The other end of the indicator begins to appear from above of the selected pane.
![image](https://github.com/bdlukaa/fluent_ui/assets/40336192/5603eb4f-a437-4da5-ae26-612a018e4c24)

3. The top half of the indicator fades out
![image](https://github.com/bdlukaa/fluent_ui/assets/40336192/fcd2fb7a-d173-4a27-8f38-dee35448a48a)
![image](https://github.com/bdlukaa/fluent_ui/assets/40336192/e7b58cd5-aad8-4c1b-b83c-bfb7215723df)
![image](https://github.com/bdlukaa/fluent_ui/assets/40336192/48283f8b-aa07-4217-89be-b3c9a144421b)

4. The indicator shrink to the normal size:
![image](https://github.com/bdlukaa/fluent_ui/assets/40336192/c8f80186-23e2-4623-90ed-3a4a915a5d84)
![image](https://github.com/bdlukaa/fluent_ui/assets/40336192/37f0b590-9d4b-4ca2-b71a-61fd2d26f0ce)

These animations seem not linear.

Looks like we only have the last animation currently.

**Comment by bdlukaa** [comment] 2023-12-29 18:59
Duplicate of #540

**Closed by bdlukaa** 2023-12-29 18:59 UTC
