### ISSUE TITLE
TextFormBox.initialValue removed break Flutter Pattern 🐛 

### ISSUE THREAD

**Issue by jacobaraujo7** [bdlukaa/fluent_ui#755] opened 2023-03-05 22:51 UTC
I understand removing the initial value of the TextBox, however the TextFormBox needs to keep the property, as it is a Flutter standard.
For the TextFormBox, using a controller is unnecessary in most cases, given its use with the ancestor Form widget.

This should be considered a bug as it breaks the pattern used in the TextFormField and will confuse people, in addition to causing unnecessary breaks

**Comment by bdlukaa** [comment] 2023-03-06 09:32
Duplicate of #749

Fixed in https://github.com/bdlukaa/fluent_ui/commit/cb03216304ae7ca6a2d1d91cbdc290d175118baf

**Closed** 2023-03-06 09:32 UTC
