### ISSUE TITLE
About tabview tabs rebuild

### ISSUE THREAD

**Issue by mechanical118** [bdlukaa/fluent_ui#924] opened 2023-08-31 11:27 UTC
I’m developing a desktop app using a tabView as the main widget. When the "reorder" event occurs within the tabView, I’m noticed that after reordering, all tab bodies between the oldIndex and newIndex are being build again. I think rebuilding process becomes problematic, for example, when dealing with large files within tab bodies, causing significant loading times. If I don't handle it asynchronously, the tab bar reorders fine, but the tab bodies still function in their previous order.(when I use futurebuilder, tabBody follow correct order but take quite some time.
I want if it is possible that when reorder function is called, the tab bodies' pointers are swapped, then I could potentially avoid the need for rebuilding. Because I’m not highly experienced in development, I acknowledge the possibility of misunderstandings on that.
Thank you for reading text.

**Comment by bdlukaa** [comment] 2023-09-01 10:43
You can use an `AutomaticKeepAliveClientMixin`.

Duplicate of #910

**Closed** 2023-09-01 10:43 UTC
