### ISSUE TITLE
Flutter web has error scrollbar.dart: missing second positional argument about PointerDeviceKind

### ISSUE THREAD

**Issue by JeromeGsq** [bdlukaa/fluent_ui#34] opened 2021-05-19 21:26 UTC
Hi, 
You should add the PointerDeviceKind: 

```
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fluent_ui-2.0.0/lib/src/controls/utils/scrollbar.dart:152:31: Error:
Too few positional arguments: 2 required, 1 given.
    if (isPointerOverScrollbar(event.position)) {                       
                              ^                                         
Waiting for connection from debug service on Chrome...             27,2s
```

**Comment by bdlukaa** [comment] 2021-05-19 21:37
Duplicate of #16 . https://github.com/bdlukaa/fluent_ui/pull/35 should fix it

**Closed by bdlukaa** 2021-05-19 21:37 UTC
