### ISSUE TITLE
The method 'VoidCallbackIntent' isn't defined for the class '_TreeViewItem' 🐛 

### ISSUE THREAD

**Issue by wesche50** [bdlukaa/fluent_ui#591] opened 2022-10-24 12:51 UTC
**Describe the bug**
After upgrading from fluent_ui 4.0.0-pre.2 to fluent_ui 4.0.3 the application is no longer buildable. 
Build process is giving me the following error message:
.../fluent_ui-4.0.3/lib/src/controls/navigation/tree_view.dart:833:21: Error: The method 'VoidCallbackIntent' isn't defined for the class '_TreeViewItem'.

SameErrors in same file on:
- tree_view.dart:840:21
- tree_view.dart:852:21

Info: Our application does use the tree_view component

**To Reproduce**
1. Upgrade fluent_ui dependency from 4.0.0-pre.2 to 4.0.3
2. Run flutter clean
3. Run flutter packages pub get
4. Run all code generators
5. Run flutter run -d windows 

**Expected behavior**
Build process should run without errors and the application should launch

**Additional context**
Information about the system:
Windows x64
Flutter channel (fvm): stable
Flutter version (fvm): 3.0.5

**Comment by bdlukaa** [comment] 2022-10-24 21:16
Please, use the latest flutter version.

Duplicate of #561

**Closed by bdlukaa** 2022-10-24 21:16 UTC
Labels: duplicate
